[package]
name = "tokio-tcp-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.9.2"
dhat = "0.3.3"
hyperfine = "1.19"
flamegraph = "0.6.9"
